%% Question 1 : Structural analysis

% Inputs
clear all; clc;
syms u1(t) u2(t)
ST_input(1,:) = {u1, u2};
ST_input(2,:) = {'u_1\\left(t\\right)', 'u_2\\left(t\\right)'};

% Measurements
syms y1(t) y2(t) y3(t) d(t)
ST_meas(1,:) = {y1, y2, y3, d};
ST_meas(2,:) = {'y1\\left(t\\right)', 'y2\\left(t\\right)', 'y3\\left(t\\right)','d(t)'};

% Parameters
syms J1 J2 J3 k1 k2 b1 b2 b3
ST_parameters(1,:) = {J1, J2, J3, k1, k2, b1, b2, b3};
ST_parameters(2,:) = {'J1', 'J2', 'J3', 'k1', 'k2', 'b1', 'b2', 'b3'};

% Unknowns
syms theta1(t) theta1_d(t) omega1(t) omega1_d(t) ...
     theta2(t) theta2_d(t) omega2(t) omega2_d(t) ...
     theta3(t) theta3_d(t) omega3(t) omega3_d(t) 

ST_unknowns(1,:) = {theta1, theta1_d, omega1, omega1_d, ...
                    theta2, theta2_d, omega2, omega2_d, ...
                    theta3, theta3_d, omega3, omega3_d};

ST_unknowns(2,:) = {...
    '\\theta_1\\left(t\\right)','\\dot{\\theta}_1\\left(t\\right)',...
    '\\omega_1\\left(t\\right)','\\dot{\\omega}_1\\left(t\\right)',...
    '\\theta_2\\left(t\\right)','\\dot{\\theta}_2\\left(t\\right)',...
    '\\omega_2\\left(t\\right)','\\dot{\\omega}_2\\left(t\\right)',...
    '\\theta_3\\left(t\\right)','\\dot{\\theta}_3\\left(t\\right)',...
    '\\omega_3\\left(t\\right)','\\dot{\\omega}_3\\left(t\\right)',...
    };

ST_cons(1,:) = {'c1','c2','c3','c4','c5','c6','d7','d8','d9','d10','d11','d12','m13','m14','m15'};
ST_cons(2,:) = {'c_1','c_2','c_3','c_4','c_5','c_6','d_7','d_8','d_9','d_{10}','d_{11}','d_{12}','m_{13}','m_{14}','m_{15}'};

ST_cons(3,:) = {...
    0 == theta1_d - omega1, ...
    0 == J1*omega1_d - u1 + b1*omega1 + k1*(theta1 - theta2) + d, ...
    0 == theta2_d - omega2, ...
    0 == J2*omega2_d - u2 + b2*omega2 + k1*(theta2 - theta1) + k2*(theta2 - theta3), ...
    0 == theta3_d - omega3, ...
    0 == J3*omega3_d + b3*omega3 + k2*(theta3 - theta2), ...
    0 == theta1_d - diff(theta1,t), ...
    0 == omega1_d - diff(omega1,t), ...
    0 == theta2_d - diff(theta2,t), ...
    0 == omega2_d - diff(omega2,t), ...
    0 == theta3_d - diff(theta3,t), ...
    0 == omega3_d - diff(omega3,t), ...
    0 == y1 - theta1, ...
    0 == y2 - theta2, ...
    0 == y3 - theta3};

ST_canfail  = [1:6,13:15];
ST_domains  = ones(1,length(ST_cons(1,:))); % ???

% Automatic incMatrix generation
cons_oneway = {[],[],[],[],[],[],{theta1(t)},{omega1(t)},{theta2(t)},{omega2(t)},{theta3(t)},{omega3(t)},[],[],[]};

ST_IncMat = sa_incidencematrix(ST_cons,...
                                    ST_input,ST_meas,...
                                    ST_unknowns,cons_oneway);

ST_sys =...
    sa_create(ST_IncMat,ST_cons,...
    ST_input, ST_meas,ST_unknowns,...
    ST_domains, ST_canfail,...
	ST_parameters);

sa_disp(ST_sys);

ST_sys=sa_match(ST_sys,'rank'); % alternatively 'mso'

% Autogenerate pdf report - requires LaTeX to be installed
sa_report(ST_sys,'threeDiskSystem','pdf','analytic_expressions',true);
disp('A report has been generated with the following results:')

disp('Obtained matching:');
sa_disp(ST_sys, 't');

disp('Parity relation symbolic form:')
sa_disp(ST_sys, 's');

disp('Parity relation analytic form:')
sa_disp(ST_sys, 'a');